urdf: /home/robot/robot_ws/egomimic/robot/eva/eva_ws/src/resources/ARX_Model/X5A/urdf/X5A.urdf
topic_prefix_out: eva_ik
ik_rate: 50.0
interfaces:
  left: can1
  right: can2
ts_offset: 0.2

gripper_min: -0.18
gripper_open_value: 0.87
joint_kp: [6.225, 17.225, 18.225, 14.225, 8.225, 6.225]
joint_kd: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

cameras:
  front_img_1:
    type: "aria"
    enabled: true
    encoding: "rgb8"
    width: 640
    height: 480
  left_wrist_img:
    type: "d405"
    enabled: true
    encoding: "rgb8"
    serial_number: 218622279810
    width: 640
    height: 480
  right_wrist_img:
    type: "d405"
    enabled: true
    encoding: "rgb8"
    serial_number: 230322277025
    width: 640
    height: 480
