_target_: egomimic.pl_utils.pl_model.ModelWrapper
robomimic_model:
  _target_: egomimic.algo.hnet.PackedAlgoBase
  d_cond: 128
  domains:
  - pushshapes_sim
  - pushshapes_sim_small_circle
  ac_keys:
    pushshapes_sim: actions
    pushshapes_sim_small_circle: actions
  loss:
    _target_: egomimic.algo.hnet.GMMLoss
  outer_stage:
    _target_: egomimic.algo.hnet.HNetOuterStage
    action_dim: 2
    action_horizon: 2560
    d_model: 128
    action_head_type: gmm
    cond_encoder:
      _target_: egomimic.models.stems.cond_encoders.CondEncoderModule
      d_cond: 128
      output_key: fused_cond
      obs_specs: {}
      img_encoders: {}
    input_modules:
    - _target_: egomimic.models.stems.input_modules.ObsToken
      d_model: 128
      obs_encoder:
        _target_: egomimic.models.stems.cond_encoders.MultiEmbodimentCondEncoder
        encoders:
          pushshapes_sim:
            _target_: egomimic.models.stems.cond_encoders.CondEncoderModule
            d_cond: 128
            output_key: fused_cond
            cond_proj_widths:
            - 128
            - 128
            obs_specs:
              state_agent_obj:
                input_dim: 5
                embed_dim: 96
                widths:
                - 192
            img_encoders:
              front_img_1:
                _target_: egomimic.models.stems.visual_core.VisualCore
                in_channels: 3
                image_size: 96
                num_kp: 48
                feature_dimension: 96
                pretrained: false
                crop_aug: true
                crop_height: 86
                crop_width: 86
                crop_eval_mode: random
                crop_sample_mode: v02
          pushshapes_sim_small_circle:
            _target_: egomimic.models.stems.cond_encoders.CondEncoderModule
            d_cond: 128
            output_key: fused_cond
            cond_proj_widths:
            - 128
            - 128
            obs_specs:
              state_agent_obj:
                input_dim: 5
                embed_dim: 96
                widths:
                - 192
            img_encoders:
              front_img_1:
                _target_: egomimic.models.stems.visual_core.VisualCore
                in_channels: 3
                image_size: 96
                num_kp: 48
                feature_dimension: 96
                pretrained: false
                crop_aug: true
                crop_height: 86
                crop_width: 86
                crop_eval_mode: random
                crop_sample_mode: v02
    hnet:
      _target_: egomimic.models.hnet.hnet.HNet
      stages:
      - _target_: egomimic.models.hnet.per_embodiment_stage.PerEmbodimentStage
        sub_stages:
          pushshapes_sim:
            _target_: egomimic.models.hnet.stages.ChunkerStage
            input_hidden_dim: 128
            output_hidden_dim: 256
            target_compression_ratio: 3.0
            ratio_loss_weight: 0.03
            cond_key: null
            down_interface: first_token
            up_interface: duplicate
            router_interface: cossim
            grab_prev_end: true
            residual_mixer: mlp
            residual_mixer_kwargs:
              n_layers: 4
          pushshapes_sim_small_circle:
            _target_: egomimic.models.hnet.stages.ChunkerStage
            input_hidden_dim: 128
            output_hidden_dim: 256
            target_compression_ratio: 3.0
            ratio_loss_weight: 0.03
            cond_key: null
            down_interface: first_token
            up_interface: duplicate
            router_interface: cossim
            grab_prev_end: true
            residual_mixer: mlp
            residual_mixer_kwargs:
              n_layers: 4
      - _target_: egomimic.models.hnet.per_embodiment_stage.PerEmbodimentStage
        sub_stages:
          pushshapes_sim:
            _target_: egomimic.models.hnet.stages.ChunkerStage
            input_hidden_dim: 256
            output_hidden_dim: 512
            target_compression_ratio: 3.0
            ratio_loss_weight: 0.03
            cond_key: null
            down_interface: first_token
            up_interface: duplicate
            router_interface: cossim
            grab_prev_end: true
            residual_mixer: mlp
            residual_mixer_kwargs:
              n_layers: 4
          pushshapes_sim_small_circle:
            _target_: egomimic.models.hnet.stages.ChunkerStage
            input_hidden_dim: 256
            output_hidden_dim: 512
            target_compression_ratio: 3.0
            ratio_loss_weight: 0.03
            cond_key: null
            down_interface: first_token
            up_interface: duplicate
            router_interface: cossim
            grab_prev_end: true
            residual_mixer: mlp
            residual_mixer_kwargs:
              n_layers: 4
      - _target_: egomimic.models.hnet.stages.ComputeStage
        input_hidden_dim: 512
        output_hidden_dim: 512
        cond_key: null
        d_cond: 0
        causal: true
        main_network:
          arch_layout: T6
          d_model: 512
          d_intermediate: 1536
          num_heads: 8
          cond: false
          rotary_emb_dim: 64
          dropout: 0.0
          resid_dropout: 0.0
    gmm_heads:
      pushshapes_sim:
        _target_: egomimic.models.heads.gmm_head.GMMActionHead
        d_model: 128
        action_dim: 2
        num_modes: 32
        chunk_len: 4
        min_std: 0.0001
        std_activation: softplus
        low_noise_eval: true
        head_hidden_dim: 512
        head_n_layers: 3
      pushshapes_sim_small_circle:
        _target_: egomimic.models.heads.gmm_head.GMMActionHead
        d_model: 128
        action_dim: 2
        num_modes: 32
        chunk_len: 4
        min_std: 0.0001
        std_activation: softplus
        low_noise_eval: true
        head_hidden_dim: 512
        head_n_layers: 3
  episode_level_transforms:
  - _target_: egomimic.algo.hnet.episode_transforms.PadHoldStill
    n_pad: 100
enable_grad_norm: true
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0
scheduler:
  _target_: egomimic.utils.schedulers.warmup_cosine_scheduler
  _partial_: true
  max_steps: 200000
  warmup_steps: 2000
  warmup_start_factor: 0.1
  eta_min: 1.0e-06
