defaults:
  - model: hpt_cotrain_flow_eve_aria_right_arm_full
  - visualization: eve_aria_right_arm_cartesian
  - paths: default
  - trainer: ddp
  - debug: null
  - logger: wandb_offline
  - data: obj_eve_aria_local_full
  - callbacks: checkpoints_full
  - data_schematic: eve_aria_right_arm
  - evaluator: eval_hpt
  - override hydra/launcher: submitit
  - _self_

name: ${oc.env:RUN_NAME,obj_BC_2ID_8EV_pg4_full}
description: ${oc.env:RUN_NAME,obj_BC_2ID_8EV_pg4_full}
ckpt_path: null
mode: train

hydra:
  run:
    dir: ${oc.env:EVE_HYDRA_RUN_DIR,./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}}
  sweep:
    dir: ${oc.env:EVE_HYDRA_RUN_DIR,./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}}

launch_params:
  gpus_per_node: 4
  nodes: 1

seed: 42

trainer:
  max_epochs: 2000
  min_epochs: 2000
  check_val_every_n_epoch: 100
  num_sanity_val_steps: 0
  limit_train_batches: 100
  limit_val_batches: 64
  precision: bf16-mixed

norm_stats:
  sample_frac: 0.1
  num_workers: 4
  save_cache_dir: ${hydra:runtime.output_dir}
  precomputed_norm_path: null
reject_outliers: false
