defaults:
  - train_zarr_cartesian
  - override model: pi05/bc_eva
  - override data: generic/multiview_cartesian/eva
  - override trainer: ddp/pi
  - override evaluator: pi/base
  - override hydra/launcher: submitit_pace
