defaults:
  - paths: default
  - debug: null
  - data: eva
  - callbacks: checkpoints
  - model: hpt_bc_flow_eva
  - trainer: ddp
  - logger: wandb
  - data_schematic: hpt
  - override hydra/launcher: submitit
  - _self_

name: test
description: test
ckpt_path: null
train: true
eval: false

eval_class:
  _target_: egomimic.scripts.evaluation.Eve
  mode: real
  arm: both
  eval_path: "./logs/eval/${name}_${now:%Y-%m-%d_%H-%M-%S}"

hydra:
  run:
    # Dir should be experiment_name/description_{timestamp}
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}

launch_params:
  gpus_per_node: 1
  nodes: 1

seed: 42

norm_stat_fraction: 1.0 # fraction of dataset to calculate norm stats over (out of 1.0)
