defaults:
  - model: hpt_cotrain_flow_transformer
  - paths: default
  - trainer: ddp
  - debug: null
  - logger: wandb
  - data: multi_data
  - callbacks: checkpoints
  - override hydra/launcher: submitit
  - _self_

name: cotrain
description: cotrain_cup
ckpt_path: null
train: true
eval: false

eval_class:
  _target_ : egomimic.scripts.evaluation.Eve
  mode: real
  arm: both
  eval_path: "./logs/eval/${name}_${now:%Y-%m-%d_%H-%M-%S}"

hydra:
  run:
    # Dir should be experiment_name/description_{timestamp}
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}

launch_params:
  gpus_per_node: 1
  nodes: 1

data_schematic: # Dynamically fill in these shapes from the dataset
  _target_: rldb.utils.DataSchematic
  norm_mode: quantile
  schematic_dict:
    aria_bimanual:
      front_img_1:
        key_type: camera_keys
        lerobot_key: observations.images.front_img_1
      ee_pose:
        key_type: proprio_keys
        lerobot_key: observations.state.ee_pose
      actions_cartesian:
        key_type: action_keys
        lerobot_key: actions_cartesian
      embodiment:
        key_type: metadata_keys
        lerobot_key: metadata.embodiment
    eve_bimanual:
      front_img_1:
        key_type: camera_keys
        lerobot_key: observations.images.aria_rgb_cam
      ee_pose:
        key_type: proprio_keys
        lerobot_key: observations.state.ee_pose
      joint_positions:
        key_type: proprio_keys
        lerobot_key: observations.state.joints_hand
      actions_cartesian:
        key_type: action_keys
        lerobot_key: actions_cartesian
      actions_joints:
        key_type: action_keys
        lerobot_key: actions_joints
      embodiment:
        key_type: metadata_keys
        lerobot_key: metadata.embodiment
  viz_img_key: 
    aria_bimanual:
      front_img_1
    eve_bimanual:
      front_img_1