defaults:
  - hpt_cotrain_flow_eve_aria_wrist

robomimic_model:
  trunk:
    action_horizon: 8                        # OLD value
  head_specs:
    eve_bimanual:
      action_horizon: 100
      num_inference_steps: 50
      time_dist: "beta"
      infer_ac_dims:
        eve_bimanual: 12
      model:
        nblocks: 6
        cond_dim: 256
        hidden_dim: 128
        act_dim: 12
        act_seq: 100
        n_heads: 4
        dropout: 0.1
        mlp_layers: 4
        mlp_ratio: 4
    eve_bimanual_actions_joints:
      action_horizon: 100
      num_inference_steps: 50
      time_dist: "beta"
      infer_ac_dims:
        eve_bimanual: 34
      model:
        nblocks: 6
        cond_dim: 256
        hidden_dim: 128
        act_dim: 34
        act_seq: 100
        n_heads: 4
        dropout: 0.1
        mlp_layers: 4
        mlp_ratio: 4
    aria_bimanual:
      action_horizon: 100
      num_inference_steps: 50
      time_dist: "beta"
      infer_ac_dims:
        aria_bimanual: 12
      model:
        nblocks: 6
        cond_dim: 256
        hidden_dim: 128
        act_dim: 12
        act_seq: 100
        n_heads: 4
        dropout: 0.1
        mlp_layers: 4
        mlp_ratio: 4

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-4
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 2000
  eta_min: 1e-5
