defaults:
  - hpt_cotrain_enc_dec_base

robomimic_model:
  # domains: ["aria_right_arm", "eve_right_arm"]
  domains: ["aria_right_arm", "faive"]
  diffusion: true 
  head_specs:
    shared: null
    aria_right_arm: 
      _target_: egomimic.models.fm_policy.FMPolicy
      action_horizon: 100
      num_inference_steps: 50
      pooling: null
      time_dist: "beta"
      infer_ac_dims:
        aria_right_arm: 6
      model:
        _target_: egomimic.models.denoising_nets.CrossTransformer
        nblocks: 6
        cond_dim: 256
        hidden_dim: 128
        act_dim: 6
        act_seq: 100
        n_heads: 4
        dropout: 0.1
        mlp_layers: 4
        mlp_ratio: 4

    faive: 
      _target_: egomimic.models.fm_policy.FMPolicy
      action_horizon: 100
      num_inference_steps: 50
      pooling: null
      time_dist: "beta"
      infer_ac_dims:
        faive: 7
      model:
        _target_: egomimic.models.denoising_nets.CrossTransformer
        nblocks: 6
        cond_dim: 256
        hidden_dim: 128
        act_dim: 7
        act_seq: 100
        n_heads: 4
        dropout: 0.1
        mlp_layers: 4 
        mlp_ratio: 4
        
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-4
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 1400
  eta_min: 1e-5