defaults:
  - hpt_cotrain_keypoints_base

robomimic_model:
  ac_keys:
    eva_bimanual: "actions_eva_cart_aria_keypoints"
    aria_bimanual: "actions_eva_cart_aria_keypoints"
  shared_ac_key: "actions_eva_cart_aria_keypoints"

  6dof: true
  diffusion: true

  head_specs:
    aria_bimanual: null
    eva_bimanual: null
    shared:
      _target_: egomimic.models.fm_policy.FMPolicy
      action_horizon: 100
      num_inference_steps: 50
      pooling: null
      padding: "zero"
      time_dist: "beta"
      model:
        _target_: egomimic.models.denoising_nets.CrossTransformer
        nblocks: 8
        cond_dim: 256
        hidden_dim: 256
        act_dim: 256
        act_seq: 100
        n_heads: 4
        dropout: 0.1
        mlp_layers: 4
        mlp_ratio: 4
      embodiment_specs:
        eva_bimanual:
          ac_dims: 14
          encoder:
            _target_: egomimic.models.codec.mlp.MLPProjection
            input_dim: 14
            hidden_dim: 256
            n_layers: 2
            output_dim: 256
          decoder:
            _target_: egomimic.models.codec.mlp.MLPProjection
            input_dim: 256
            hidden_dim: 256
            n_layers: 2
            output_dim: 14
        aria_bimanual:
          ac_dims: 138
          encoder:
            _target_: egomimic.models.codec.mlp.MLPProjection
            input_dim: 138
            hidden_dim: 256
            n_layers: 7
            output_dim: 256
          decoder:
            _target_: egomimic.models.codec.mlp.MLPProjection
            input_dim: 256
            hidden_dim: 256
            n_layers: 7
            output_dim: 138

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-4
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 1800
  eta_min: 1e-5
