# HPT pushshapes simpleconv: identical to circle_regression but swaps the front
# encoder ResNet -> SimpleConvEncoder. extends hpt_pushshapes_circle_regression.
defaults:
  - hpt_pushshapes_circle_regression
  - _self_

robomimic_model:
  encoder_specs:
    front_img_1:
      _target_: egomimic.models.hpt_simpleconv_encoder.SimpleConvEncoder
      output_dim: 128
