#!/usr/bin/env python3
"""
Plot unified metric curves from CSV tables generated by extract_wandb_metrics.py.

Creates plots with:
- X-axis: Number of scenes (4, 6, 8)
- Y-axis: Metric value
- Two curves: 4 operators and 8 operators
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Tuple, Optional
import re


def is_error_metric(metric_name: str) -> bool:
    """
    Determine if a metric is an error metric (lower is better) or success metric (higher is better).
    
    Error metrics typically contain: mse, error, loss, distance, kl, frechet
    Success metrics typically contain: accuracy, success, rate
    
    Returns:
        True if error metric (lower is better), False if success metric (higher is better)
    """
    metric_lower = metric_name.lower()
    
    # Error indicators (lower is better)
    error_keywords = ['mse', 'error', 'loss', 'distance', 'kl', 'frechet']
    for keyword in error_keywords:
        if keyword in metric_lower:
            return True
    
    # Success indicators (higher is better)
    success_keywords = ['accuracy', 'success', 'rate']
    for keyword in success_keywords:
        if keyword in metric_lower:
            return False
    
    # Default to error metric if uncertain
    return True


def format_metric_name(metric_name: str) -> str:
    """
    Format metric name for display in plot titles and labels.
    
    Converts snake_case to Title Case and removes common prefixes.
    """
    # Remove common prefixes
    name = metric_name.replace('aria_bimanual_actions_cartesian_', '')
    name = name.replace('Valid/', '')
    
    # Convert snake_case to Title Case
    name = name.replace('_', ' ').title()
    
    # Handle special cases
    name = name.replace('Mse', 'MSE')
    name = name.replace('Kl', 'KL')
    name = name.replace('M8', ' (M=8)')
    
    return name


def plot_metric_in_subplot(ax, df: pd.DataFrame, metric_name: str):
    """
    Plot a single metric with two curves (4 operators vs 8 operators) in a subplot.
    
    Args:
        ax: Matplotlib axes object to plot on
        df: DataFrame with scenes as index and operators (4, 8) as columns
        metric_name: Name of the metric (for title and labeling)
    """
    # Determine metric type
    is_error = is_error_metric(metric_name)
    metric_display = format_metric_name(metric_name)
    y_label = f"{metric_display} ({'↓' if is_error else '↑'})"
    
    # Extract data
    scenes = df.index.tolist()
    values_4 = df[4].tolist()
    values_8 = df[8].tolist()
    
    # Plot two curves
    ax.plot(scenes, values_4, 
            marker='o', linestyle='-', linewidth=2, markersize=6,
            label='4 operators', color='#2E86AB')  # Blue
    
    ax.plot(scenes, values_8,
            marker='s', linestyle='--', linewidth=2, markersize=6,
            label='8 operators', color='#A23B72')  # Purple/Red
    
    # Customize plot
    ax.set_xlabel('Number of Scenes', fontsize=10, fontweight='bold')
    ax.set_ylabel(y_label, fontsize=10, fontweight='bold')
    ax.set_title(metric_display, fontsize=11, fontweight='bold', pad=10)
    
    # Set x-axis ticks to exact scene values
    ax.set_xticks(scenes)
    ax.set_xticklabels([str(s) for s in scenes])
    
    # Add grid
    ax.grid(True, alpha=0.3, linestyle='--')
    
    # Add legend (smaller for subplots)
    ax.legend(loc='best', fontsize=9, framealpha=0.9)


def main():
    """Main function to plot all metrics from CSV files."""
    
    # Base results directory
    base_results_dir = Path("/coc/flash7/bli678/Shared/EgoVerse/results")
    
    # Try to find CSV files in subdirectories or directly in results
    # Check for mixed_diversity_fold_clothes subdirectory first
    results_dir = base_results_dir / "mixed_diversity_fold_clothes"
    if not results_dir.exists():
        # Fall back to base results directory
        results_dir = base_results_dir
    
    # Output directory for plots (same as where CSV files are)
    output_dir = results_dir
    
    if not results_dir.exists():
        print(f"Error: Results directory not found: {results_dir}")
        return
    
    # Find all CSV files (excluding the unified table and hash files)
    csv_files = [f for f in results_dir.glob("*.csv") 
                 if "unified" not in f.name.lower() and "hash" not in f.name.lower()]
    
    if not csv_files:
        print(f"Warning: No CSV files found in {results_dir}")
        return
    
    print(f"Found {len(csv_files)} CSV files to plot")
    print(f"Results directory: {results_dir}\n")
    
    # Collect all valid dataframes
    metric_data = []
    
    # Process each CSV file and collect data
    for csv_path in sorted(csv_files):
        metric_name = csv_path.stem  # Filename without extension
        
        print(f"Processing: {metric_name}")
        
        try:
            # Read CSV file
            df = pd.read_csv(csv_path, index_col=0)
            
            # Verify structure - the index should be scenes (4, 6, 8)
            # The index name might be 'Scenes' or might be unnamed
            # Convert index to integers if they're strings
            try:
                df.index = [int(x) for x in df.index]
            except (ValueError, TypeError):
                print(f"  Warning: Could not convert index to integers, skipping")
                continue
            
            # Verify we have the expected columns (might be strings or integers)
            # Convert column names to integers if needed
            df.columns = [int(col) if str(col).isdigit() else col for col in df.columns]
            
            if 4 not in df.columns or 8 not in df.columns:
                print(f"  Warning: Missing operator columns (4 or 8), skipping")
                print(f"    Available columns: {list(df.columns)}")
                continue
            
            # Verify we have scene data
            if len(df) == 0:
                print(f"  Warning: No data in CSV, skipping")
                continue
            
            # Store for unified plotting
            metric_data.append((metric_name, df))
            print(f"  ✓ Loaded successfully")
            
        except Exception as e:
            print(f"  Error processing {csv_path}: {e}")
            continue
    
    if not metric_data:
        print("Error: No valid metrics to plot")
        return
    
    # Define the desired metric order
    metric_order = [
        'reverse_kl',
        'paired_mse_avg',
        'final_mse_avg',
        'frechet_gauss_min',
        'frechet_gauss_avg',
        'frechet_gauss_max'
    ]
    
    # Create a function to get sort key for metric ordering
    def get_metric_order_key(metric_name):
        metric_lower = metric_name.lower()
        for idx, order_name in enumerate(metric_order):
            if order_name in metric_lower:
                return idx
        return 999  # Put unknown metrics at the end
    
    # Sort metrics according to desired order
    metric_data_sorted = sorted(metric_data, key=lambda x: get_metric_order_key(x[0]))
    
    # Create unified figure with 2x3 subplots
    print(f"\nCreating unified figure with {len(metric_data_sorted)} metrics...")
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    axes = axes.flatten()  # Flatten to 1D array for easier indexing
    
    # Plot each metric in a subplot in the specified order
    for idx, (metric_name, df) in enumerate(metric_data_sorted):
        if idx >= 6:  # Only plot first 6 metrics (2x3 grid)
            print(f"  Warning: More than 6 metrics found, only plotting first 6")
            break
        plot_metric_in_subplot(axes[idx], df, metric_name)
    
    # Hide unused subplots if we have fewer than 6 metrics
    for idx in range(len(metric_data_sorted), 6):
        axes[idx].set_visible(False)
    
    # Add overall title
    fig.suptitle('Mixed Diversity', 
                 fontsize=16, fontweight='bold', y=0.995)
    
    # Improve layout
    plt.tight_layout(rect=[0, 0, 1, 0.98])  # Leave space for suptitle
    
    # Save unified figure
    unified_plot_path = output_dir / "mixed_diversity_plot.png"
    output_dir.mkdir(parents=True, exist_ok=True)
    plt.savefig(unified_plot_path, dpi=300, bbox_inches='tight', format='png')
    print(f"  Saved unified plot to: {unified_plot_path}")
    
    # Close figure to free memory
    plt.close(fig)
    
    print(f"\n{'='*60}")
    print(f"Summary:")
    print(f"  - Processed {len(metric_data)} metrics")
    print(f"  - Created unified figure: all_metrics_unified_plot.png")
    print(f"  - Output directory: {output_dir}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
