#!/usr/bin/env python3
"""
Plot motion diversity metrics from CSV table generated by motion_diversity_table.py.

Creates unified figure with:
- X-axis: Number of operators (4, 8, 12)
- Y-axis: Metric value
- 2x3 grid of subplots, one for each metric
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Tuple, Optional
import re


def is_error_metric(metric_name: str) -> bool:
    """
    Determine if a metric is an error metric (lower is better) or success metric (higher is better).
    
    Error metrics typically contain: mse, error, loss, distance, kl, frechet
    Success metrics typically contain: accuracy, success, rate
    
    Returns:
        True if error metric (lower is better), False if success metric (higher is better)
    """
    metric_lower = metric_name.lower()
    
    # Error indicators (lower is better)
    error_keywords = ['mse', 'error', 'loss', 'distance', 'kl', 'frechet']
    for keyword in error_keywords:
        if keyword in metric_lower:
            return True
    
    # Success indicators (higher is better)
    success_keywords = ['accuracy', 'success', 'rate']
    for keyword in success_keywords:
        if keyword in metric_lower:
            return False
    
    # Default to error metric if uncertain
    return True


def format_metric_name(metric_name: str) -> str:
    """
    Format metric name for display in plot titles and labels.
    
    Converts column names to readable format.
    """
    # Already formatted from the CSV, but handle any edge cases
    if "Reverse KL" in metric_name:
        return "Reverse KL (M=8)"
    elif "Paired MSE" in metric_name:
        return "Paired MSE Avg"
    elif "Final MSE" in metric_name:
        return "Final MSE Avg"
    elif "Frechet Gauss Min" in metric_name:
        return "Frechet Gauss Min"
    elif "Frechet Gauss Avg" in metric_name:
        return "Frechet Gauss Avg"
    elif "Frechet Gauss Max" in metric_name:
        return "Frechet Gauss Max"
    
    return metric_name


def plot_metric_in_subplot(ax, df: pd.DataFrame, metric_name: str):
    """
    Plot a single metric with operators on x-axis in a subplot.
    
    Args:
        ax: Matplotlib axes object to plot on
        df: DataFrame with operators as index and metrics as columns
        metric_name: Name of the metric column (for title and labeling)
    """
    # Determine metric type
    is_error = is_error_metric(metric_name)
    metric_display = format_metric_name(metric_name)
    y_label = f"{metric_display} ({'↓' if is_error else '↑'})"
    
    # Extract data
    operators = df.index.tolist()
    values = df[metric_name].tolist()
    
    # Plot curve
    ax.plot(operators, values, 
            marker='o', linestyle='-', linewidth=2, markersize=8,
            color='#2E86AB')  # Blue
    
    # Customize plot
    ax.set_xlabel('Number of Operators', fontsize=10, fontweight='bold')
    ax.set_ylabel(y_label, fontsize=10, fontweight='bold')
    ax.set_title(metric_display, fontsize=11, fontweight='bold', pad=10)
    
    # Set x-axis ticks to exact operator values
    ax.set_xticks(operators)
    ax.set_xticklabels([str(op) for op in operators])
    
    # Add grid
    ax.grid(True, alpha=0.3, linestyle='--')
    
    # Add value labels on points
    for op, val in zip(operators, values):
        if val is not None and not pd.isna(val):
            ax.annotate(f'{val:.3f}', (op, val), 
                       textcoords="offset points", xytext=(0,10), 
                       ha='center', fontsize=8)


def main():
    """Main function to plot motion diversity metrics from CSV file."""
    
    # Input CSV file
    csv_path = Path("/coc/flash7/bli678/Shared/EgoVerse/results/motion_diversity_fold_clothes/motion_diversity_metrics.csv")
    
    # Output directory for plots (same as CSV location)
    output_dir = csv_path.parent
    
    if not csv_path.exists():
        print(f"Error: CSV file not found: {csv_path}")
        print("Please run motion_diversity_table.py first to generate the CSV file.")
        return
    
    print(f"Reading CSV file: {csv_path}")
    
    try:
        # Read CSV file
        df = pd.read_csv(csv_path, index_col=0)
        
        # Verify structure
        if df.index.name != 'Operators':
            # Try to set index name if it's in the first column
            if 'Operators' in df.columns:
                df = df.set_index('Operators')
            else:
                print(f"Warning: Unexpected structure, using first column as index")
        
        # Convert index to integers if they're strings
        try:
            df.index = [int(x) for x in df.index]
        except (ValueError, TypeError):
            print(f"Error: Could not convert index to integers")
            return
        
        # Sort by operators
        df = df.sort_index()
        
        print(f"Loaded data with {len(df)} operators and {len(df.columns)} metrics")
        print(f"Operators: {list(df.index)}")
        print(f"Metrics: {list(df.columns)}")
        
        # Define metric order (matching the table order)
        metric_order = [
            'Reverse KL (M=8)',
            'Paired MSE Avg',
            'Final MSE Avg',
            'Frechet Gauss Min',
            'Frechet Gauss Avg',
            'Frechet Gauss Max'
        ]
        
        # Filter to only include metrics that exist in the DataFrame
        available_metrics = [m for m in metric_order if m in df.columns]
        
        if not available_metrics:
            print("Error: No matching metrics found in CSV file")
            return
        
        print(f"\nCreating unified figure with {len(available_metrics)} metrics...")
        
        # Create unified figure with 2x3 subplots
        fig, axes = plt.subplots(2, 3, figsize=(18, 12))
        axes = axes.flatten()  # Flatten to 1D array for easier indexing
        
        # Plot each metric in a subplot
        for idx, metric_name in enumerate(available_metrics):
            if idx >= 6:  # Only plot first 6 metrics (2x3 grid)
                print(f"  Warning: More than 6 metrics found, only plotting first 6")
                break
            plot_metric_in_subplot(axes[idx], df, metric_name)
        
        # Hide unused subplots if we have fewer than 6 metrics
        for idx in range(len(available_metrics), 6):
            axes[idx].set_visible(False)
        
        # Add overall title
        fig.suptitle('Motion Diversity', 
                     fontsize=16, fontweight='bold', y=0.995)
        
        # Improve layout
        plt.tight_layout(rect=[0, 0, 1, 0.98])  # Leave space for suptitle
        
        # Save unified figure
        plot_path = output_dir / "motion_diversity_plot.png"
        output_dir.mkdir(parents=True, exist_ok=True)
        plt.savefig(plot_path, dpi=300, bbox_inches='tight', format='png')
        print(f"  Saved unified plot to: {plot_path}")
        
        # Close figure to free memory
        plt.close(fig)
        
        print(f"\n{'='*60}")
        print(f"Summary:")
        print(f"  - Processed {len(available_metrics)} metrics")
        print(f"  - Created unified figure: motion_diversity_plot.png")
        print(f"  - Output directory: {output_dir}")
        print(f"{'='*60}")
        
    except Exception as e:
        print(f"Error processing CSV file: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
