#!/usr/bin/env python3
"""
Plot unified scene diversity metric curves from CSV tables generated by scene_diversity_table.py.

Creates unified figure with:
- X-axis: Number of scenes (1, 2, 4, 8, 16)
- Y-axis: Metric value
- 5 curves per subplot (one for each time value: 3.75, 7.5, 15, 30, 60)
- 2x3 grid of subplots, one for each metric
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Tuple, Optional
import re


def is_error_metric(metric_name: str) -> bool:
    """
    Determine if a metric is an error metric (lower is better) or success metric (higher is better).
    
    Error metrics typically contain: mse, error, loss, distance, kl, frechet
    Success metrics typically contain: accuracy, success, rate
    
    Returns:
        True if error metric (lower is better), False if success metric (higher is better)
    """
    metric_lower = metric_name.lower()
    
    # Error indicators (lower is better)
    error_keywords = ['mse', 'error', 'loss', 'distance', 'kl', 'frechet']
    for keyword in error_keywords:
        if keyword in metric_lower:
            return True
    
    # Success indicators (higher is better)
    success_keywords = ['accuracy', 'success', 'rate']
    for keyword in success_keywords:
        if keyword in metric_lower:
            return False
    
    # Default to error metric if uncertain
    return True


def format_metric_name(metric_name: str) -> str:
    """
    Format metric name for display in plot titles and labels.
    
    Converts metric name to readable format.
    """
    # Remove common prefixes
    name = metric_name.replace('aria_bimanual_actions_cartesian_', '')
    name = name.replace('Valid/', '')
    
    # Convert snake_case to Title Case
    name = name.replace('_', ' ').title()
    
    # Handle special cases
    name = name.replace('Mse', 'MSE')
    name = name.replace('Kl', 'KL')
    name = name.replace('M8', ' (M=8)')
    
    return name


def plot_metric_in_subplot(ax, df: pd.DataFrame, metric_name: str):
    """
    Plot a single metric with 5 curves (one for each time value) in a subplot.
    
    Args:
        ax: Matplotlib axes object to plot on
        df: DataFrame with scenes as index and time as columns
        metric_name: Name of the metric (for title and labeling)
    """
    # Determine metric type
    is_error = is_error_metric(metric_name)
    metric_display = format_metric_name(metric_name)
    y_label = f"{metric_display} ({'↓' if is_error else '↑'})"
    
    # Extract data
    scenes = df.index.tolist()
    
    # Define time values and their styling
    time_values = [3.75, 7.5, 15, 30, 60]
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']  # Distinct colors
    markers = ['o', 's', '^', 'D', 'v']  # Different markers
    linestyles = ['-', '--', '-.', ':', '-']  # Different line styles
    
    # Plot 5 curves (one for each time value)
    for idx, time in enumerate(time_values):
        if time not in df.columns:
            continue
        
        values = df[time].tolist()
        # Filter out None/NaN values for plotting
        valid_scenes = []
        valid_values = []
        for s, v in zip(scenes, values):
            if v is not None and not pd.isna(v):
                valid_scenes.append(s)
                valid_values.append(v)
        
        if len(valid_scenes) > 0:
            ax.plot(valid_scenes, valid_values,
                   marker=markers[idx], linestyle=linestyles[idx], 
                   linewidth=2, markersize=6,
                   label=f'{time} min', color=colors[idx])
    
    # Customize plot
    ax.set_xlabel('Number of Scenes', fontsize=10, fontweight='bold')
    ax.set_ylabel(y_label, fontsize=10, fontweight='bold')
    ax.set_title(metric_display, fontsize=11, fontweight='bold', pad=10)
    
    # Set x-axis ticks to exact scene values
    ax.set_xticks(scenes)
    ax.set_xticklabels([str(s) for s in scenes])
    
    # Add grid
    ax.grid(True, alpha=0.3, linestyle='--')
    
    # Add legend (smaller for subplots)
    ax.legend(loc='best', fontsize=8, framealpha=0.9, ncol=1)


def main():
    """Main function to plot scene diversity metrics from CSV files."""
    
    # Input directory with CSV files
    results_dir = Path("/coc/flash7/bli678/Shared/EgoVerse/results/scene_diversity_fold_clothes")
    
    # Output directory for plots (same as CSV location)
    output_dir = results_dir
    
    if not results_dir.exists():
        print(f"Error: Results directory not found: {results_dir}")
        print("Please run scene_diversity_table.py first to generate the CSV files.")
        return
    
    # Find all CSV files (excluding any unified table if it exists)
    csv_files = [f for f in results_dir.glob("*.csv") 
                 if "unified" not in f.name.lower() and "hash" not in f.name.lower()]
    
    if not csv_files:
        print(f"Warning: No CSV files found in {results_dir}")
        return
    
    print(f"Found {len(csv_files)} CSV files to plot")
    print(f"Results directory: {results_dir}\n")
    
    # Collect all valid dataframes
    metric_data = []
    
    # Process each CSV file and collect data
    for csv_path in sorted(csv_files):
        metric_name = csv_path.stem  # Filename without extension
        
        print(f"Processing: {metric_name}")
        
        try:
            # Read CSV file
            df = pd.read_csv(csv_path, index_col=0)
            
            # Verify structure - the index should be scenes
            if df.index.name != 'Scenes':
                # Try to set index name if it's in the first column
                if 'Scenes' in df.columns:
                    df = df.set_index('Scenes')
                else:
                    print(f"  Warning: Unexpected structure, using first column as index")
            
            # Convert index to integers if they're strings
            try:
                df.index = [int(x) for x in df.index]
            except (ValueError, TypeError):
                print(f"  Warning: Could not convert index to integers, skipping")
                continue
            
            # Convert column names to floats if they're strings
            df.columns = [float(col) if isinstance(col, str) and col.replace('.', '').isdigit() else col 
                         for col in df.columns]
            
            # Sort by scenes
            df = df.sort_index()
            
            # Verify we have scene data
            if len(df) == 0:
                print(f"  Warning: No data in CSV, skipping")
                continue
            
            # Store for unified plotting
            metric_data.append((metric_name, df))
            print(f"  ✓ Loaded successfully")
            
        except Exception as e:
            print(f"  Error processing {csv_path}: {e}")
            continue
    
    if not metric_data:
        print("Error: No valid metrics to plot")
        return
    
    # Define the desired metric order
    metric_order = [
        'reverse_kl',
        'paired_mse_avg',
        'final_mse_avg',
        'frechet_gauss_min',
        'frechet_gauss_avg',
        'frechet_gauss_max'
    ]
    
    # Create a function to get sort key for metric ordering
    def get_metric_order_key(metric_name):
        metric_lower = metric_name.lower()
        for idx, order_name in enumerate(metric_order):
            if order_name in metric_lower:
                return idx
        return 999  # Put unknown metrics at the end
    
    # Sort metrics according to desired order
    metric_data_sorted = sorted(metric_data, key=lambda x: get_metric_order_key(x[0]))
    
    # Create unified figure with 2x3 subplots
    print(f"\nCreating unified figure with {len(metric_data_sorted)} metrics...")
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    axes = axes.flatten()  # Flatten to 1D array for easier indexing
    
    # Plot each metric in a subplot in the specified order
    for idx, (metric_name, df) in enumerate(metric_data_sorted):
        if idx >= 6:  # Only plot first 6 metrics (2x3 grid)
            print(f"  Warning: More than 6 metrics found, only plotting first 6")
            break
        plot_metric_in_subplot(axes[idx], df, metric_name)
    
    # Hide unused subplots if we have fewer than 6 metrics
    for idx in range(len(metric_data_sorted), 6):
        axes[idx].set_visible(False)
    
    # Add overall title
    fig.suptitle('Scene Diversity', 
                 fontsize=16, fontweight='bold', y=0.995)
    
    # Improve layout
    plt.tight_layout(rect=[0, 0, 1, 0.98])  # Leave space for suptitle
    
    # Save unified figure
    plot_path = output_dir / "scene_diversity_plot.png"
    output_dir.mkdir(parents=True, exist_ok=True)
    plt.savefig(plot_path, dpi=300, bbox_inches='tight', format='png')
    print(f"  Saved unified plot to: {plot_path}")
    
    # Close figure to free memory
    plt.close(fig)
    
    print(f"\n{'='*60}")
    print(f"Summary:")
    print(f"  - Processed {len(metric_data_sorted)} metrics")
    print(f"  - Created unified figure: scene_diversity_plot.png")
    print(f"  - Output directory: {output_dir}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
